version: '3'
services:
  web-flask-celery:
    build:
      context: .
      dockerfile: Dockerfile
      # image: diegobrasil/curl-requester:1.0
    ports:
      - "8000:5000"
    volumes:
      - .:/src
    stop_signal: SIGINT
    depends_on:
      - rabbitmq
  rabbitmq:
    hostname: "rabbit"
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - '15672:15672'
      - '5672:5672'
  #   depends_on: 
  #     - redis
  # redis:
  #   image: redislabs/redismod
  #   ports:
  #     - '6379:6379'